import type { Metadata } from "next";
import { Instrument_Serif, DM_Sans } from 'next/font/google';
import "./globals.css";
import SmoothScrollProvider from '@/components/providers/smooth-scroll-provider';


const instrumentSerif = Instrument_Serif({
	subsets: ['latin'],
	weight: '400',
	variable: '--font-serif',
});

const dmSans = DM_Sans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: "Loris Swider",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="fr"
			className={`${instrumentSerif.variable} ${dmSans.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<SmoothScrollProvider>{children}</SmoothScrollProvider>
			</body>
		</html>
	);
}